### ISSUE TITLE
question

### ISSUE THREAD

**Issue by blht-chen** [sautee/battery-state-of-charge-estimation#3]
Have you tried using only fixed temperature datasets as training sets and then directly generalizing them to variable temperature datasets (10-20 drift ones)

**Comment by sautee** [comment]
@blht-chen haven't used fixed temperature datasets. That is a good experiment to try. Which NN architecture do you think will return optimal results with a fixed temp dataset?

**Comment by blht-chen** [comment]
No, no, you may have misunderstood my question. I mean that the training set is a fixed environment dataset, just like the Panasonic n10degC, 0degC, 10degC, 25deg dataset you used in your experiment, and then you predict the capacity at the corresponding temperature. Do you think the model trained with this dataset alone can be generalized to 10-20 degrees training without additional training

**Comment by blht-chen** [comment]
i used TCN+BiLSTM to train dataset,but it can't generalized to Variable ambient temperature dataset Only a certain trend

**Comment by sautee** [comment]
I've used models trained on LG cell to infer Panasonic SOC. The inference losses are generally higher vs models trained using the cell itself. I've trained models on combined LG and Panasonic data, but haven't verified with other datasets. I think you'll need much more data +training to generalize.
